// Test IDs used throughout the app for stable e2e/unit testing.
export const TESTIDS = {
  bulkPrepareAll: "bulk-prepare-all-button",
  bulkDownloadMp4: "bulk-download-mp4-button",
  bulkDownloadMp3: "bulk-download-mp3-button",
  bulkReset: "bulk-reset-button",
  bulkResetConfirm: "bulk-reset-confirm-button",
  bulkResetCancel: "bulk-reset-cancel-button",
  searchInput: "links-search-input",
  platformFilter: "platform-filter-select",
  statusFilter: "status-filter-select",
  kpiTotal: "kpi-total",
  kpiReady: "kpi-ready",
  kpiErrors: "kpi-errors",
  kpiPreparing: "kpi-preparing",
  themeToggle: "theme-toggle",
  rowPrepare: (infId) => `row-prepare-button-${infId}`,
  rowDownloadMp4: (infId) => `row-download-mp4-button-${infId}`,
  rowDownloadMp3: (infId) => `row-download-mp3-button-${infId}`,
  rowRetry: (infId) => `row-retry-button-${infId}`,
  rowStatus: (infId) => `row-status-chip-${infId}`,
  rowThumbnail: (infId) => `row-thumbnail-${infId}`,
  rowErrorExpand: (infId) => `row-error-expand-${infId}`,
  rowCopyLink: (infId) => `row-copy-link-button-${infId}`,
  rowOpenExternal: (infId) => `row-open-external-button-${infId}`,
};
